name: sycamore_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  serverpod: 2.0.0

dev_dependencies:
  custom_lint: ^0.6.4
  lints: '>=3.0.0 <5.0.0'
